export const disclaimer = {
  "disclaimer.title": "Disclaimer - Free Online Developer Tools",
  "disclaimer.description":
    "Important disclaimer and limitations of liability for our free online developer tools and services.",
  "disclaimer.keywords":
    "disclaimer, limitations, liability, developer tools disclaimer, legal notice",
  "disclaimer.heading": "Disclaimer",
  "disclaimer.lastUpdated": "Last updated: December 15, 2025",
  "disclaimer.intro":
    "This disclaimer governs your use of our website and developer tools. By using our services, you acknowledge that you have read and understood this disclaimer.",
  "disclaimer.general.title": "General Disclaimer",
  "disclaimer.general.content":
    'The information on this website and within our tools is provided on an "as is" basis. To the fullest extent permitted by law, we exclude all representations, warranties, and conditions relating to our website and the use of this website.',
  "disclaimer.accuracy.title": "Accuracy of Information",
  "disclaimer.accuracy.content":
    "While we strive to provide accurate and up-to-date information, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, products, services, or related graphics contained on our tools.",
  "disclaimer.toolLimitations.title": "Tool Limitations",
  "disclaimer.toolLimitations.content":
    "Our developer tools are provided for informational and educational purposes only. The results generated by our tools should be verified independently before use in production environments or critical applications.",
  "disclaimer.noWarranty.title": "No Warranty",
  "disclaimer.noWarranty.content":
    'We do not warrant that our tools will meet your requirements or that the operation of our tools will be uninterrupted or error-free. We provide our services "as is" without any warranty of any kind.',
  "disclaimer.externalLinks.title": "External Links",
  "disclaimer.externalLinks.content":
    "Our website may contain links to third-party websites or services. We have no control over the content, privacy policies, or practices of these external sites and assume no responsibility for them.",
  "disclaimer.userResponsibility.title": "User Responsibility",
  "disclaimer.userResponsibility.content":
    "You are responsible for verifying the accuracy of outputs from our tools; Using our tools in accordance with applicable laws and regulations; Ensuring your use of our tools complies with any third-party terms or agreements; Backing up your data and implementing appropriate security measures",
  "disclaimer.liability.title": "Limitation of Liability",
  "disclaimer.liability.content":
    "In no event will we be liable for any loss or damage including, without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of or in connection with the use of our website or tools.",
  "disclaimer.professionalAdvice.title": "Professional Advice",
  "disclaimer.professionalAdvice.content":
    "Nothing on our website or in our tools constitutes professional advice. For specific technical, legal, or business advice, please consult with qualified professionals in the relevant field.",
  "disclaimer.updates.title": "Updates and Changes",
  "disclaimer.updates.content":
    "We reserve the right to update this disclaimer at any time without notice. Changes will be effective immediately upon posting. Your continued use of our services after changes constitutes acceptance of the updated disclaimer.",
  "disclaimer.severability.title": "Severability",
  "disclaimer.severability.content":
    "If any provision of this disclaimer is found to be unenforceable, the remaining provisions will continue to be valid and enforceable to the fullest extent permitted by law.",
  "disclaimer.applicableLaw.title": "Governing Law",
  "disclaimer.applicableLaw.content":
    "This disclaimer shall be governed by and construed in accordance with applicable laws, and any disputes will be subject to the exclusive jurisdiction of the relevant courts.",
  "disclaimer.contact.title": "Questions",
  "disclaimer.contact.content":
    "If you have any questions about this disclaimer, please contact us:",
  "disclaimer.contact.email": "legal@devtools.app",
  "disclaimer.commitment.title": "Our Commitment",
  "disclaimer.commitment.content":
    "While we provide this disclaimer for legal protection, we remain committed to providing reliable, useful tools and transparent communication with our users.",
};
